mongo:
  databaseName: Tulip
  connectionString: mongodb://localhost:27017

spawn:
  world: world
  x: -4.5
  y: 66.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

scoreboard:
  title: "&d&lFree For All"
  lines:
    spawn:
      - "{sidebar}"
      - "&f&lStats"
      - " &f&l● &rKills: &d{kills}"
      - " &f&l● &rDeaths: &d{deaths}"
      - " &f&l● &rKDR: &d{KDR}"
      - ""
      - "&f&lServer"
      - " &f&l● &rOnline: &d{online}"
      - ""
      - "&dtulip.club"
      - "{sidebar}"
    in-game:
      - "{sidebar}"
      - "&fPlaying FFA:"
      - " &d{kit}"
      - ""
      - " &fKills: &d{kills}"
      - " &fDeaths: &d{deaths}"
      - ""
      - " &fKillstreak: &d{ks}"
      - " &fPlayers: &d{players}"
      - ""
      - "&fYour Ping: &d{ping} ms"
      - ""
      - "&dtulip.club"
      - "{sidebar}"
    #In case if profile fails to load, this will be displayed to prevent console errors.
    failed:
      - "{sidebar}"
      - "&c&lFailed to load your profile"
      - "&c&lPlease try relogging."
      - "&c&lIf the issue persists,"
      - "&c&lcontact an admin."
      - "{sidebar}"

hotbar-items:
  GAME_MENU:
    material: DIAMOND_SWORD
    slot: 0
    durability: 0
    name: "&dGame Menu &7(Right Click)"
    command: "play"
    lore:
      - "&7&oClick to open the game menu."
  KIT_LAYOUT:
    material: BOOK
    slot: 1
    durability: 0
    name: "&dEdit Kit Layout &7(Right Click)"
    command: "kitlayout"
    lore:
      - "&7&oClick to edit your kit layout."
  SHOP:
    material: DIAMOND
    slot: 4
    durability: 0
    name: "&dShop &7(Right Click)"
    command: "shop"
    lore:
      - "&7&oClick to open the shop."
  STATS:
    material: NETHER_STAR
    slot: 7
    durability: 0
    name: "&dStats &7(Right Click)"
    command: "stats"
    lore:
      - "&7&oClick to view your stats."
  SETTINGS:
    material: SKULL_ITEM
    slot: 8
    durability: 0
    name: "&dSettings &7(Left Click)"
    command: "ffasettings"
    lore:
      - "&7&oClick to open the settings menu."
